### ISSUE TITLE
"Sharing is only supported for boot loader classes because bootstrap classpath has been appended"

### ISSUE THREAD

**Issue by QubitPi** [paion-data/aristotle#15]
When I did the following:

```
git clone git@github.com:paion-data/aristotle.git
cd aristotle
mvn clean package
```

My console threw a Maven error:

![page 2(2)](https://github.com/user-attachments/assets/276a9388-2b59-4774-9cf6-8f02e5201dbe)

`[ERROR] OpenJDK 64-Bit Server VM warning: Sharing is only supported for boot loader classes because bootstrap classpath has been appended` doesn't break the build though, but we need an investigation on __why this would happen__, because this could be a source of potential bug in the future.

My JDK and Maven versions are the following:

```console
$ java -version
openjdk version "17.0.11" 2024-04-16
OpenJDK Runtime Environment Homebrew (build 17.0.11+0)
OpenJDK 64-Bit Server VM Homebrew (build 17.0.11+0, mixed mode, sharing)

$ mvn -v
Apache Maven 3.9.8 (36645f6c9b5079805ea5009217e36f2cffd34256)
Java version: 17.0.11, vendor: Homebrew
Default locale: en_US, platform encoding: UTF-8
OS name: "mac os x", version: "13.1", arch: "x86_64", family: "mac"
```

**Comment by Doom9527** [comment]
I also get the following error when I run the `mvn clean package`: 
`Java HotSpot(TM) 64-Bit Server VM warning: Sharing is only supported for boot loader classes because bootstrap classpath has been appended`

**Comment by Doom9527** [comment]
I have read in several forums that we had better ignore this warning, and the forums consistently suggest that it will not make any difference, and trying to solve it may cause some other problems.
<img width="544" alt="1727160207132" src="https://github.com/user-attachments/assets/e2fc3b37-ac85-4f83-ad54-0074bad3ba47">
https://stackoverflow.com/questions/54205486/how-to-avoid-sharing-is-only-supported-for-boot-loader-classes-because-bootstra

**Comment by QubitPi** [comment]
Let me investigate it a little bit and I will post here later

**Comment by QubitPi** [comment]
[This is caused by Mockito](https://github.com/mockito/mockito/issues/3111). As long as tests pass, we don't worry too much about production then.
